/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : MyGrammar.g
 *     -                            On : 2024-10-03 19:07:22
 *     -                 for the lexer : MyGrammarLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
MyGrammarLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pMyGrammarLexer, which is returned from a call to MyGrammarLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pMyGrammarLexer are  as follows:
 *
 *  - 
 void
      pMyGrammarLexer->T__23(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__24(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__25(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__26(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__27(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__28(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__29(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__30(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__31(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__32(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__33(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__34(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__35(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__36(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__37(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__38(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__39(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__40(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__41(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__42(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__43(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__44(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__45(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__46(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__47(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__48(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__49(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__50(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__51(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__52(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__53(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__54(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__55(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__56(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__57(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__58(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__59(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__60(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__61(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__62(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__63(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__64(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__65(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__66(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__67(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__68(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__69(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__70(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__71(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__72(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__73(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__74(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__75(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__76(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__77(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__78(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__79(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__80(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__81(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__82(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__83(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__84(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__85(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__86(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__87(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__88(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__89(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__90(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__91(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__92(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__93(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__94(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__95(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__96(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__97(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__98(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__99(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->T__100(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->IDENTIFIER(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->LETTER(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->CHARACTER_LITERAL(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->STRING_LITERAL(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->HEX_LITERAL(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->DECIMAL_LITERAL(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->OCTAL_LITERAL(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->HexDigit(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->IntegerTypeSuffix(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->FLOATING_POINT_LITERAL(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->Exponent(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->FloatTypeSuffix(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->EscapeSequence(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->OctalEscape(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->UnicodeEscape(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->WS(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->COMMENT(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->LINE_COMMENT(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->LINE_COMMAND(pMyGrammarLexer)
 *  - 
 void
      pMyGrammarLexer->Tokens(pMyGrammarLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_MyGrammarLexer_H
#define _MyGrammarLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct MyGrammarLexer_Ctx_struct MyGrammarLexer, * pMyGrammarLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
MyGrammarLexer

 */
struct MyGrammarLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mT__23)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__24)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__25)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__26)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__27)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__28)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__29)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__30)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__31)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__32)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__33)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__34)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__35)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__36)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__37)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__38)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__39)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__40)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__41)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__42)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__43)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__44)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__45)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__46)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__47)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__48)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__49)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__50)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__51)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__52)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__53)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__54)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__55)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__56)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__57)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__58)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__59)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__60)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__61)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__62)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__63)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__64)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__65)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__66)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__67)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__68)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__69)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__70)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__71)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__72)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__73)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__74)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__75)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__76)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__77)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__78)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__79)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__80)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__81)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__82)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__83)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__84)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__85)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__86)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__87)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__88)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__89)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__90)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__91)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__92)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__93)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__94)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__95)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__96)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__97)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__98)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__99)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mT__100)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mIDENTIFIER)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mLETTER)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mCHARACTER_LITERAL)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mSTRING_LITERAL)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mHEX_LITERAL)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mDECIMAL_LITERAL)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mOCTAL_LITERAL)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mHexDigit)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mIntegerTypeSuffix)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mFLOATING_POINT_LITERAL)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mExponent)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mFloatTypeSuffix)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mEscapeSequence)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mOctalEscape)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mUnicodeEscape)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mWS)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mCOMMENT)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mLINE_COMMENT)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mLINE_COMMAND)	(struct MyGrammarLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct MyGrammarLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct MyGrammarLexer_Ctx_struct * ctx);
    void	    (*free)   (struct MyGrammarLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pMyGrammarLexer MyGrammarLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pMyGrammarLexer MyGrammarLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__23      23
#define T__24      24
#define T__25      25
#define T__26      26
#define T__27      27
#define T__28      28
#define T__29      29
#define T__30      30
#define T__31      31
#define T__32      32
#define T__33      33
#define T__34      34
#define T__35      35
#define T__36      36
#define T__37      37
#define T__38      38
#define T__39      39
#define T__40      40
#define T__41      41
#define T__42      42
#define T__43      43
#define T__44      44
#define T__45      45
#define T__46      46
#define T__47      47
#define T__48      48
#define T__49      49
#define T__50      50
#define T__51      51
#define T__52      52
#define T__53      53
#define T__54      54
#define T__55      55
#define T__56      56
#define T__57      57
#define T__58      58
#define T__59      59
#define T__60      60
#define T__61      61
#define T__62      62
#define T__63      63
#define T__64      64
#define T__65      65
#define T__66      66
#define T__67      67
#define T__68      68
#define T__69      69
#define T__70      70
#define T__71      71
#define T__72      72
#define T__73      73
#define T__74      74
#define T__75      75
#define T__76      76
#define T__77      77
#define T__78      78
#define T__79      79
#define T__80      80
#define T__81      81
#define T__82      82
#define T__83      83
#define T__84      84
#define T__85      85
#define T__86      86
#define T__87      87
#define T__88      88
#define T__89      89
#define T__90      90
#define T__91      91
#define T__92      92
#define T__93      93
#define T__94      94
#define T__95      95
#define T__96      96
#define T__97      97
#define T__98      98
#define T__99      99
#define T__100      100
#define CHARACTER_LITERAL      4
#define COMMENT      5
#define DECIMAL_LITERAL      6
#define EscapeSequence      7
#define Exponent      8
#define FLOATING_POINT_LITERAL      9
#define FloatTypeSuffix      10
#define HEX_LITERAL      11
#define HexDigit      12
#define IDENTIFIER      13
#define IntegerTypeSuffix      14
#define LETTER      15
#define LINE_COMMAND      16
#define LINE_COMMENT      17
#define OCTAL_LITERAL      18
#define OctalEscape      19
#define STRING_LITERAL      20
#define UnicodeEscape      21
#define WS      22
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for MyGrammarLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
